-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 08, 2020 at 05:32 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `scroll`
--

-- --------------------------------------------------------

--
-- Table structure for table `lore`
--

CREATE TABLE `lore` (
  `id` int(11) NOT NULL,
  `content` text NOT NULL,
  `date` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `lore`
--

INSERT INTO `lore` (`id`, `content`, `date`) VALUES
(1, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ita nemo beato beatior. Tria genera bonorum; Tu quidem reddes; Duo Reges: constructio interrete. Sint ista Graecorum; Quid ergo? </p>\n\n<p>Quae contraria sunt his, malane? Tollenda est atque extrahenda radicitus. Aliter enim nosmet ipsos nosse non possumus. Optime, inquam. An potest cupiditas finiri? Cyrenaici quidem non recusant; Velut ego nunc moveor. Sed residamus, inquit, si placet. </p>\n\n<p>Scrupulum, inquam, abeunti; Equidem etiam Epicurum, in physicis quidem, Democriteum puto. Aliter enim nosmet ipsos nosse non possumus. Immo alio genere; </p>\n\n', 1602076755),
(2, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Optime, inquam. Polycratem Samium felicem appellabant. Non laboro, inquit, de nomine. Qui ita affectus, beatum esse numquam probabis; </p>\n\n<p>Non est ista, inquam, Piso, magna dissensio. Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Equidem etiam Epicurum, in physicis quidem, Democriteum puto. </p>\n\n<p>Immo videri fortasse. Bonum incolumis acies: misera caecitas. Et quod est munus, quod opus sapientiae? Et nemo nimium beatus est; Quamquam tu hanc copiosiorem etiam soles dicere. Tuo vero id quidem, inquam, arbitratu. Sed in rebus apertissimis nimium longi sumus. </p>\n\n', 1602076755),
(3, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. An tu me de L. Quae cum essent dicta, discessimus. Ergo, inquit, tibi Q. Duo Reges: constructio interrete. Sint ista Graecorum; Aliter homines, aliter philosophos loqui putas oportere? </p>\n\n<p>Quibus ego vehementer assentior. Confecta res esset. Proclivi currit oratio. Quamquam id quidem licebit iis existimare, qui legerint. Quae duo sunt, unum facit. </p>\n\n<p>Dat enim intervalla et relaxat. Traditur, inquit, ab Epicuro ratio neglegendi doloris. Quis hoc dicit? </p>\n\n', 1602076755),
(4, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ergo hoc loco intellegit honestum? Idem adhuc; </p>\n\n<p>In schola desinis. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Cur id non ita fit? Duo Reges: constructio interrete. </p>\n\n<p>Quae similitudo in genere etiam humano apparet. Istam voluptatem, inquit, Epicurus ignorat? Nihil opus est exemplis hoc facere longius. Quae duo sunt, unum facit. </p>\n\n', 1602076755),
(5, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Itaque hic ipse iam pridem est reiectus; Memini vero, inquam; Perge porro; </p>\n\n<p>Videsne, ut haec concinant? Omnia peccata paria dicitis. An vero, inquit, quisquam potest probare, quod perceptfum, quod. Illa tamen simplicia, vestra versuta. Ostendit pedes et pectus. Tibi hoc incredibile, quod beatissimum. </p>\n\n<p>Sit enim idem caecus, debilis. Quo modo? Respondent extrema primis, media utrisque, omnia omnibus. Nos cum te, M. Praeteritis, inquit, gaudeo. Aliter homines, aliter philosophos loqui putas oportere? Itaque hic ipse iam pridem est reiectus; Immo videri fortasse. </p>\n\n', 1602076756),
(6, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proclivi currit oratio. Dici enim nihil potest verius. Nam Pyrrho, Aristo, Erillus iam diu abiecti. Quae duo sunt, unum facit. </p>\n\n<p>Quam ob rem tandem, inquit, non satisfacit? Quaerimus enim finem bonorum. Minime vero istorum quidem, inquit. Primum in nostrane potestate est, quid meminerimus? Suo genere perveniant ad extremum; Sed quid sentiat, non videtis. </p>\n\n<p>Zenonis est, inquam, hoc Stoici. Duo Reges: constructio interrete. Quis hoc dicit? Videsne quam sit magna dissensio? Quid sequatur, quid repugnet, vident. Laboro autem non sine causa; </p>\n\n', 1602076825),
(7, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tu vero, inquam, ducas licet, si sequetur; Terram, mihi crede, ea lanx et maria deprimet. Tibi hoc incredibile, quod beatissimum. Qui convenit? Duo Reges: constructio interrete. </p>\n\n<p>Restatis igitur vos; Inde igitur, inquit, ordiendum est. At ille pellit, qui permulcet sensum voluptate. Hic ambiguo ludimur. Gloriosa ostentatio in constituendo summo bono. </p>\n\n<p>Recte, inquit, intellegis. Prodest, inquit, mihi eo esse animo. </p>\n\n', 1602076825),
(8, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quid sentiat, non videtis. Pugnant Stoici cum Peripateticis. At multis malis affectus. Quid sequatur, quid repugnet, vident. Duo enim genera quae erant, fecit tria. Nosti, credo, illud: Nemo pius est, qui pietatem-; </p>\n\n<p>Res enim se praeclare habebat, et quidem in utraque parte. Duo Reges: constructio interrete. Dici enim nihil potest verius. Quorum sine causa fieri nihil putandum est. Sedulo, inquam, faciam. Magna laus. </p>\n\n<p>Ergo id est convenienter naturae vivere, a natura discedere. Expectoque quid ad id, quod quaerebam, respondeas. Ad eos igitur converte te, quaeso. Gerendus est mos, modo recte sentiat. Quid de Pythagora? </p>\n\n', 1602076825),
(9, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Avaritiamne minuis? Scrupulum, inquam, abeunti; Primum divisit ineleganter; Nobis aliter videtur, recte secusne, postea; </p>\n\n<p>Iam in altera philosophiae parte. Tollenda est atque extrahenda radicitus. Cur igitur, inquam, res tam dissimiles eodem nomine appellas? Duo Reges: constructio interrete. Haec para/doca illi, nos admirabilia dicamus. </p>\n\n<p>Reguli reiciendam; Nobis aliter videtur, recte secusne, postea; Quid de Pythagora? Sed quid attinet de rebus tam apertis plura requirere? Itaque ab his ordiamur. </p>\n\n', 1602076825),
(10, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos cum te, M. Tu quidem reddes; Duo enim genera quae erant, fecit tria. Quid de Pythagora? Cur id non ita fit? Proclivi currit oratio. </p>\n\n<p>Stoici scilicet. Haec dicuntur inconstantissime. Esse enim quam vellet iniquus iustus poterat inpune. Qui est in parvis malis. </p>\n\n<p>Duo Reges: constructio interrete. Ratio enim nostra consentit, pugnat oratio. Invidiosum nomen est, infame, suspectum. Itaque fecimus. Scaevolam M. Hanc quoque iucunditatem, si vis, transfer in animum; </p>\n\n', 1602076825),
(11, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erit enim mecum, si tecum erit. Omnes enim iucundum motum, quo sensus hilaretur. Quam si explicavisset, non tam haesitaret. Ratio enim nostra consentit, pugnat oratio. Quo tandem modo? Est enim effectrix multarum et magnarum voluptatum. Duo Reges: constructio interrete. Eaedem enim utilitates poterunt eas labefactare atque pervertere. </p>\n\n<p>Si quicquam extra virtutem habeatur in bonis. Ita prorsus, inquam; </p>\n\n<p>Si longus, levis dictata sunt. Omnia peccata paria dicitis. Beatus sibi videtur esse moriens. Respondent extrema primis, media utrisque, omnia omnibus. Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Sed nunc, quod agimus; </p>\n\n', 1602076825),
(12, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Si quae forte-possumus. Reguli reiciendam; Istic sum, inquit. Mihi enim erit isdem istis fortasse iam utendum. </p>\n\n<p>Quorum altera prosunt, nocent altera. Cum praesertim illa perdiscere ludus esset. Duo Reges: constructio interrete. Aliter enim explicari, quod quaeritur, non potest. </p>\n\n<p>Sed quid sentiat, non videtis. Rationis enim perfectio est virtus; </p>\n\n', 1602076825),
(13, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aufert enim sensus actionemque tollit omnem. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Cur post Tarentum ad Archytam? Eam tum adesse, cum dolor omnis absit; Duo Reges: constructio interrete. Certe non potest. Itaque contra est, ac dicitis; </p>\n\n<p>Invidiosum nomen est, infame, suspectum. Occultum facinus esse potuerit, gaudebit; An tu me de L. </p>\n\n<p>Ita credo. Tamen a proposito, inquam, aberramus. Estne, quaeso, inquam, sitienti in bibendo voluptas? Age sane, inquam. Praeclarae mortes sunt imperatoriae; Deinde dolorem quem maximum? </p>\n\n', 1602076825),
(14, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid igitur, inquit, eos responsuros putas? Quis non odit sordidos, vanos, leves, futtiles? Frater et T. Efficiens dici potest. Numquam facies. Est enim effectrix multarum et magnarum voluptatum. </p>\n\n<p>Beatus sibi videtur esse moriens. Ubi ut eam caperet aut quando? </p>\n\n<p>Duo Reges: constructio interrete. Istam voluptatem, inquit, Epicurus ignorat? Ubi ut eam caperet aut quando? At hoc in eo M. Itaque his sapiens semper vacabit. Tollenda est atque extrahenda radicitus. </p>\n\n', 1602076827),
(15, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed haec quidem liberius ab eo dicuntur et saepius. Ego vero isti, inquam, permitto. Quis hoc dicit? Suam denique cuique naturam esse ad vivendum ducem. Invidiosum nomen est, infame, suspectum. Non est igitur voluptas bonum. Ego vero isti, inquam, permitto. Sed ego in hoc resisto; </p>\n\n<p>Duo Reges: constructio interrete. Itaque contra est, ac dicitis; Vide, quaeso, rectumne sit. Certe, nisi voluptatem tanti aestimaretis. Cur haec eadem Democritus? </p>\n\n<p>Hic nihil fuit, quod quaereremus. At ego quem huic anteponam non audeo dicere; Tria genera bonorum; Sed quid sentiat, non videtis. Nobis aliter videtur, recte secusne, postea; Quid autem habent admirationis, cum prope accesseris? Istam voluptatem perpetuam quis potest praestare sapienti? Sed ille, ut dixi, vitiose. Illa tamen simplicia, vestra versuta. </p>\n\n', 1602076827),
(16, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Videsne quam sit magna dissensio? Indicant pueri, in quibus ut in speculis natura cernitur. Scrupulum, inquam, abeunti; Graece donan, Latine voluptatem vocant. Sed plane dicit quod intellegit. Duo Reges: constructio interrete. </p>\n\n<p>Videsne, ut haec concinant? Cur haec eadem Democritus? Duarum enim vitarum nobis erunt instituta capienda. Scrupulum, inquam, abeunti; Tibi hoc incredibile, quod beatissimum. Illud dico, ea, quae dicat, praeclare inter se cohaerere. </p>\n\n<p>Et non ex maxima parte de tota iudicabis? Quid turpius quam sapientis vitam ex insipientium sermone pendere? Tecum optime, deinde etiam cum mediocri amico. Utilitatis causa amicitia est quaesita. Conferam avum tuum Drusum cum C. Gerendus est mos, modo recte sentiat. </p>\n\n', 1602076827),
(17, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Summum ením bonum exposuit vacuitatem doloris; Quam si explicavisset, non tam haesitaret. Dici enim nihil potest verius. Memini vero, inquam; Refert tamen, quo modo. </p>\n\n<p>Duo Reges: constructio interrete. Age sane, inquam. Nam de isto magna dissensio est. Quae cum essent dicta, discessimus. Hoc loco tenere se Triarius non potuit. Quae quo sunt excelsiores, eo dant clariora indicia naturae. De hominibus dici non necesse est. Duo enim genera quae erant, fecit tria. </p>\n\n<p>Et nemo nimium beatus est; Praeclarae mortes sunt imperatoriae; Quam si explicavisset, non tam haesitaret. Omnes enim iucundum motum, quo sensus hilaretur. </p>\n\n', 1602076827),
(18, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Istam voluptatem perpetuam quis potest praestare sapienti? An tu me de L. Si longus, levis; At ille pellit, qui permulcet sensum voluptate. Minime vero istorum quidem, inquit. Cur, nisi quod turpis oratio est? </p>\n\n<p>Conferam avum tuum Drusum cum C. Nunc haec primum fortasse audientis servire debemus. Age, inquies, ista parva sunt. Tu vero, inquam, ducas licet, si sequetur; Quid de Platone aut de Democrito loquar? Praeteritis, inquit, gaudeo. </p>\n\n<p>Duo Reges: constructio interrete. Quae sequuntur igitur? Sed tamen intellego quid velit. Sed ad rem redeamus; At ille pellit, qui permulcet sensum voluptate. Ita prorsus, inquam; Pauca mutat vel plura sane; A mene tu? </p>\n\n', 1602076827),
(19, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Esse enim quam vellet iniquus iustus poterat inpune. Quod autem ratione actum est, id officium appellamus. Eadem nunc mea adversum te oratio est. Quo plebiscito decreta a senatu est consuli quaestio Cn. Duo Reges: constructio interrete. Quid autem habent admirationis, cum prope accesseris? </p>\n\n<p>An haec ab eo non dicuntur? Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Nam de isto magna dissensio est. Erat enim Polemonis. </p>\n\n<p>Quid Zeno? Efficiens dici potest. Videsne, ut haec concinant? Age sane, inquam. Facillimum id quidem est, inquam. Tum mihi Piso: Quid ergo? </p>\n\n', 1602076827),
(20, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scrupulum, inquam, abeunti; Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Bonum patria: miserum exilium. Bonum negas esse divitias, praeposìtum esse dicis? </p>\n\n<p>Duo Reges: constructio interrete. Sed ad rem redeamus; Comprehensum, quod cognitum non habet? Si quae forte-possumus. Nihil enim iam habes, quod ad corpus referas; Quae est igitur causa istarum angustiarum? Omnis enim est natura diligens sui. Negare non possum. </p>\n\n<p>Haeret in salebra. Nobis aliter videtur, recte secusne, postea; Quippe: habes enim a rhetoribus; Vide, quaeso, rectumne sit. </p>\n\n', 1602076827),
(21, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non potes, nisi retexueris illa. Pauca mutat vel plura sane; Itaque his sapiens semper vacabit. Non enim iam stirpis bonum quaeret, sed animalis. Quam nemo umquam voluptatem appellavit, appellat; Certe non potest. Duo Reges: constructio interrete. Dempta enim aeternitate nihilo beatior Iuppiter quam Epicurus; </p>\n\n<p>Quid autem habent admirationis, cum prope accesseris? Immo videri fortasse. Primum divisit ineleganter; Cur iustitia laudatur? Hoc non est positum in nostra actione. </p>\n\n<p>Cur deinde Metrodori liberos commendas? Bonum integritas corporis: misera debilitas. Quo plebiscito decreta a senatu est consuli quaestio Cn. Non autem hoc: igitur ne illud quidem. Quid igitur, inquit, eos responsuros putas? Hic ambiguo ludimur. Odium autem et invidiam facile vitabis. Restatis igitur vos; </p>\n\n', 1602076827),
(22, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quare conare, quaeso. Tum Torquatus: Prorsus, inquit, assentior; Bonum integritas corporis: misera debilitas. Quod ea non occurrentia fingunt, vincunt Aristonem; Illud non continuo, ut aeque incontentae. Venit ad extremum; Magna laus. </p>\n\n<p>Duo Reges: constructio interrete. Sumenda potius quam expetenda. Ostendit pedes et pectus. Prodest, inquit, mihi eo esse animo. </p>\n\n<p>Restatis igitur vos; Quamquam haec quidem praeposita recte et reiecta dicere licebit. </p>\n\n', 1602076827),
(23, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid autem habent admirationis, cum prope accesseris? Duo Reges: constructio interrete. Itaque his sapiens semper vacabit. Mihi enim satis est, ipsis non satis. Ut in geometria, prima si dederis, danda sunt omnia. Rationis enim perfectio est virtus; Qualem igitur hominem natura inchoavit? </p>\n\n<p>Hic ambiguo ludimur. Istam voluptatem perpetuam quis potest praestare sapienti? Immo videri fortasse. Quo modo autem optimum, si bonum praeterea nullum est? Age, inquies, ista parva sunt. At multis malis affectus. Si longus, levis; Neque solum ea communia, verum etiam paria esse dixerunt. Quorum sine causa fieri nihil putandum est. </p>\n\n<p>Quonam modo? Tu quidem reddes; </p>\n\n', 1602076828),
(24, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maximus dolor, inquit, brevis est. Universa enim illorum ratione cum tota vestra confligendum puto. Sed videbimus. An eiusdem modi? </p>\n\n<p>Duo Reges: constructio interrete. Tu enim ista lenius, hic Stoicorum more nos vexat. Tollenda est atque extrahenda radicitus. Id Sextilius factum negabat. Restatis igitur vos; Haec dicuntur fortasse ieiunius; </p>\n\n<p>Minime vero istorum quidem, inquit. Itaque his sapiens semper vacabit. Vestri haec verecundius, illi fortasse constantius. </p>\n\n', 1602076828),
(25, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem etiam Epicurum, in physicis quidem, Democriteum puto. Honesta oratio, Socratica, Platonis etiam. Stoicos roga. Si quicquam extra virtutem habeatur in bonis. Duo Reges: constructio interrete. Nos commodius agimus. Duarum enim vitarum nobis erunt instituta capienda. </p>\n\n<p>Idem adhuc; An tu me de L. Tum Quintus: Est plane, Piso, ut dicis, inquit. Negat esse eam, inquit, propter se expetendam. Nemo nostrum istius generis asotos iucunde putat vivere. Sedulo, inquam, faciam. </p>\n\n<p>Quid Zeno? Hoc non est positum in nostra actione. Iam id ipsum absurdum, maximum malum neglegi. Igitur ne dolorem quidem. </p>\n\n', 1602076828),
(26, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quae duo sunt, unum facit. Utinam quidem dicerent alium alio beatiorem! Iam ruinas videres. Quod quidem iam fit etiam in Academia. Nemo nostrum istius generis asotos iucunde putat vivere. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Quis Aristidem non mortuum diligit? </p>\n\n<p>Praeclarae mortes sunt imperatoriae; Duo Reges: constructio interrete. Utilitatis causa amicitia est quaesita. Certe non potest. Animum autem reliquis rebus ita perfecit, ut corpus; Itaque ad tempus ad Pisonem omnes. </p>\n\n<p>Aufert enim sensus actionemque tollit omnem. Et non ex maxima parte de tota iudicabis? Quid, si etiam iucunda memoria est praeteritorum malorum? Tum mihi Piso: Quid ergo? </p>\n\n', 1602076828),
(27, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bestiarum vero nullum iudicium puto. Fortemne possumus dicere eundem illum Torquatum? Illa tamen simplicia, vestra versuta. Sed quid sentiat, non videtis. Duo Reges: constructio interrete. Disserendi artem nullam habuit. </p>\n\n<p>Et quod est munus, quod opus sapientiae? Ecce aliud simile dissimile. Falli igitur possumus. Quid de Platone aut de Democrito loquar? An potest cupiditas finiri? Expectoque quid ad id, quod quaerebam, respondeas. </p>\n\n<p>Nos commodius agimus. Nam ista vestra: Si gravis, brevis; Certe non potest. Itaque fecimus. </p>\n\n', 1602076828),
(28, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Collige omnia, quae soletis: Praesidium amicorum. Ita fit cum gravior, tum etiam splendidior oratio. Haeret in salebra. Sit enim idem caecus, debilis. Quare attende, quaeso. Si longus, levis; Duo Reges: constructio interrete. Istam voluptatem, inquit, Epicurus ignorat? </p>\n\n<p>Quid dubitas igitur mutare principia naturae? Bonum patria: miserum exilium. Cur, nisi quod turpis oratio est? Quod equidem non reprehendo; </p>\n\n<p>Non laboro, inquit, de nomine. Murenam te accusante defenderem. Illa tamen simplicia, vestra versuta. </p>\n\n', 1602076828),
(29, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ratio quidem vestra sic cogit. Duo Reges: constructio interrete. Sed plane dicit quod intellegit. Primum quid tu dicis breve? </p>\n\n<p>Disserendi artem nullam habuit. Tum ille: Ain tandem? Praeclare hoc quidem. Sint ista Graecorum; </p>\n\n<p>Nunc vides, quid faciat. Quid ad utilitatem tantae pecuniae? Etiam beatissimum? Maximus dolor, inquit, brevis est. Quaerimus enim finem bonorum. Quae cum dixisset, finem ille. </p>\n\n', 1602076828),
(30, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod quidem nobis non saepe contingit. Eadem nunc mea adversum te oratio est. </p>\n\n<p>Quae ista amicitia est? Quorum altera prosunt, nocent altera. Idemne, quod iucunde? Paria sunt igitur. Sed quod proximum fuit non vidit. Utilitatis causa amicitia est quaesita. </p>\n\n<p>Erit enim mecum, si tecum erit. Nunc agendum est subtilius. Non quam nostram quidem, inquit Pomponius iocans; Duo Reges: constructio interrete. Itaque fecimus. Reguli reiciendam; Sed residamus, inquit, si placet. </p>\n\n', 1602076828),
(31, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hic ambiguo ludimur. Quae ista amicitia est? Traditur, inquit, ab Epicuro ratio neglegendi doloris. Duo Reges: constructio interrete. Sed in rebus apertissimis nimium longi sumus. Numquam facies. </p>\n\n<p>Estne, quaeso, inquam, sitienti in bibendo voluptas? Sit enim idem caecus, debilis. Proclivi currit oratio. Nam quid possumus facere melius? </p>\n\n<p>Quid censes in Latino fore? Qui est in parvis malis. </p>\n\n', 1602076828),
(32, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Si enim ad populum me vocas, eum. At iam decimum annum in spelunca iacet. Duo Reges: constructio interrete. Istam voluptatem, inquit, Epicurus ignorat? Quippe: habes enim a rhetoribus; Si enim ad populum me vocas, eum. </p>\n\n<p>Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Videsne quam sit magna dissensio? Quid enim de amicitia statueris utilitatis causa expetenda vides. Graece donan, Latine voluptatem vocant. Quare conare, quaeso. </p>\n\n<p>Contemnit enim disserendi elegantiam, confuse loquitur. Bestiarum vero nullum iudicium puto. Sed nunc, quod agimus; An vero, inquit, quisquam potest probare, quod perceptfum, quod. </p>\n\n', 1602076829),
(33, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Certe, nisi voluptatem tanti aestimaretis. Occultum facinus esse potuerit, gaudebit; Tecum optime, deinde etiam cum mediocri amico. Ille enim occurrentia nescio quae comminiscebatur; Sint modo partes vitae beatae. </p>\n\n<p>Vide, quantum, inquam, fallare, Torquate. Honesta oratio, Socratica, Platonis etiam. Sed fortuna fortis; </p>\n\n<p>Duo Reges: constructio interrete. Quae sequuntur igitur? Primum Theophrasti, Strato, physicum se voluit; Aliter enim nosmet ipsos nosse non possumus. </p>\n\n', 1602076829),
(34, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ita relinquet duas, de quibus etiam atque etiam consideret. Nos vero, inquit ille; Erat enim Polemonis. Ad eos igitur converte te, quaeso. </p>\n\n<p>Duo Reges: constructio interrete. Etiam beatissimum? Quid enim possumus hoc agere divinius? </p>\n\n<p>Si id dicis, vicimus. Ille enim occurrentia nescio quae comminiscebatur; </p>\n\n', 1602076829),
(35, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qui ita affectus, beatum esse numquam probabis; In schola desinis. Duo Reges: constructio interrete. Contineo me ab exemplis. Respondeat totidem verbis. </p>\n\n<p>Immo videri fortasse. Dicimus aliquem hilare vivere; </p>\n\n<p>Quid de Platone aut de Democrito loquar? Ille incendat? Rationis enim perfectio est virtus; Minime vero, inquit ille, consentit. </p>\n\n', 1602076829),
(36, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ergo hoc loco intellegit honestum? Quis Aristidem non mortuum diligit? Minime vero istorum quidem, inquit. </p>\n\n<p>Praeteritis, inquit, gaudeo. Cave putes quicquam esse verius. Ea possunt paria non esse. Maximas vero virtutes iacere omnis necesse est voluptate dominante. Sed tamen intellego quid velit. At, si voluptas esset bonum, desideraret. Nihil opus est exemplis hoc facere longius. </p>\n\n<p>Duo Reges: constructio interrete. Iam id ipsum absurdum, maximum malum neglegi. Qui ita affectus, beatum esse numquam probabis; Traditur, inquit, ab Epicuro ratio neglegendi doloris. Et quidem, inquit, vehementer errat; Hoc simile tandem est? Apparet statim, quae sint officia, quae actiones. Quid vero? </p>\n\n', 1602076829),
(37, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis istum dolorem timet? Quid igitur, inquit, eos responsuros putas? </p>\n\n<p>At multis se probavit. Nos vero, inquit ille; Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Duo Reges: constructio interrete. </p>\n\n<p>Bonum incolumis acies: misera caecitas. An tu me de L. Comprehensum, quod cognitum non habet? Nam, ut sint illa vendibiliora, haec uberiora certe sunt. Cave putes quicquam esse verius. Quo tandem modo? Mihi enim erit isdem istis fortasse iam utendum. </p>\n\n', 1602076829),
(38, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Haec dicuntur fortasse ieiunius; Quamquam te quidem video minime esse deterritum. Duo Reges: constructio interrete. Sed fac ista esse non inportuna; Quo plebiscito decreta a senatu est consuli quaestio Cn. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Nos cum te, M. </p>\n\n<p>Disserendi artem nullam habuit. Si quidem, inquit, tollerem, sed relinquo. Istam voluptatem perpetuam quis potest praestare sapienti? Itaque hic ipse iam pridem est reiectus; </p>\n\n<p>Est, ut dicis, inquit; Tum ille: Ain tandem? Primum quid tu dicis breve? </p>\n\n', 1602076829),
(39, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et quod est munus, quod opus sapientiae? Frater et T. Huius ego nunc auctoritatem sequens idem faciam. Si quicquam extra virtutem habeatur in bonis. Haec igitur Epicuri non probo, inquam. Idemque diviserunt naturam hominis in animum et corpus. </p>\n\n<p>Sequitur disserendi ratio cognitioque naturae; Sed mehercule pergrata mihi oratio tua. </p>\n\n<p>Pollicetur certe. Duo Reges: constructio interrete. Respondeat totidem verbis. </p>\n\n', 1602076829),
(40, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Honesta oratio, Socratica, Platonis etiam. Cur post Tarentum ad Archytam? Laboro autem non sine causa; </p>\n\n<p>Nos vero, inquit ille; De vacuitate doloris eadem sententia erit. Quid Zeno? Qua tu etiam inprudens utebare non numquam. </p>\n\n<p>Quae sequuntur igitur? Negat enim summo bono afferre incrementum diem. Quae diligentissime contra Aristonem dicuntur a Chryippo. Sint modo partes vitae beatae. </p>\n\n', 1602076829),
(41, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Huius ego nunc auctoritatem sequens idem faciam. Duo Reges: constructio interrete. Audeo dicere, inquit. Indicant pueri, in quibus ut in speculis natura cernitur. Odium autem et invidiam facile vitabis. </p>\n\n<p>An hoc usque quaque, aliter in vita? Duarum enim vitarum nobis erunt instituta capienda. Falli igitur possumus. Dat enim intervalla et relaxat. Inde igitur, inquit, ordiendum est. Respondent extrema primis, media utrisque, omnia omnibus. </p>\n\n<p>Quid ergo? Praeclare hoc quidem. Ut pulsi recurrant? Non semper, inquam; Sed videbimus. </p>\n\n', 1602076830),
(42, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos commodius agimus. Praeclare hoc quidem. Pauca mutat vel plura sane; Immo videri fortasse. </p>\n\n<p>Sed ego in hoc resisto; Illi enim inter se dissentiunt. Iam id ipsum absurdum, maximum malum neglegi. Etenim semper illud extra est, quod arte comprehenditur. Si id dicis, vicimus. Negat enim summo bono afferre incrementum diem. Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio? Aliter enim nosmet ipsos nosse non possumus. </p>\n\n<p>Duo Reges: constructio interrete. Multoque hoc melius nos veriusque quam Stoici. Itaque his sapiens semper vacabit. Eaedem enim utilitates poterunt eas labefactare atque pervertere. Satis est ad hoc responsum. Quae cum dixisset paulumque institisset, Quid est? </p>\n\n', 1602076830),
(43, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Prodest, inquit, mihi eo esse animo. Iam in altera philosophiae parte. Expectoque quid ad id, quod quaerebam, respondeas. Hic ambiguo ludimur. Haec quo modo conveniant, non sane intellego. Duo Reges: constructio interrete. </p>\n\n<p>Ita nemo beato beatior. Efficiens dici potest. Tum Torquatus: Prorsus, inquit, assentior; Haeret in salebra. </p>\n\n<p>Teneo, inquit, finem illi videri nihil dolere. Quis non odit sordidos, vanos, leves, futtiles? Istam voluptatem perpetuam quis potest praestare sapienti? Quaerimus enim finem bonorum. </p>\n\n', 1602076830),
(44, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tamen a proposito, inquam, aberramus. Murenam te accusante defenderem. Ita nemo beato beatior. Quid sequatur, quid repugnet, vident. Duo Reges: constructio interrete. Num quid tale Democritus? </p>\n\n<p>Sed ille, ut dixi, vitiose. Praeclare hoc quidem. Quid de Pythagora? Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Nescio quo modo praetervolavit oratio. Primum quid tu dicis breve? </p>\n\n<p>Itaque his sapiens semper vacabit. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Cui Tubuli nomen odio non est? Cur id non ita fit? Cyrenaici quidem non recusant; Non quam nostram quidem, inquit Pomponius iocans; Cur id non ita fit? </p>\n\n', 1602076830),
(45, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qui est in parvis malis. Utilitatis causa amicitia est quaesita. Tum Torquatus: Prorsus, inquit, assentior; Ergo ita: non posse honeste vivi, nisi honeste vivatur? Duo Reges: constructio interrete. Sullae consulatum? Restatis igitur vos; Venit ad extremum; </p>\n\n<p>Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Apparet statim, quae sint officia, quae actiones. Nam de isto magna dissensio est. Haec para/doca illi, nos admirabilia dicamus. </p>\n\n<p>Multoque hoc melius nos veriusque quam Stoici. Eaedem res maneant alio modo. Facile est hoc cernere in primis puerorum aetatulis. Quid enim possumus hoc agere divinius? Satisne vobis videor pro meo iure in vestris auribus commentatus? Hoc sic expositum dissimile est superiori. An eiusdem modi? Quam ob rem tandem, inquit, non satisfacit? </p>\n\n', 1602076830),
(46, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At multis se probavit. Quis hoc dicit? Si longus, levis dictata sunt. Summae mihi videtur inscitiae. Duo Reges: constructio interrete. Quare attende, quaeso. </p>\n\n<p>Et ille ridens: Video, inquit, quid agas; Quae cum essent dicta, discessimus. Idemne, quod iucunde? Respondent extrema primis, media utrisque, omnia omnibus. Sed ego in hoc resisto; </p>\n\n<p>Is es profecto tu. Sumenda potius quam expetenda. Ut optime, secundum naturam affectum esse possit. Philosophi autem in suis lectulis plerumque moriuntur. Quantum Aristoxeni ingenium consumptum videmus in musicis? </p>\n\n', 1602076830),
(47, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quasi ego id curem, quid ille aiat aut neget. Quae contraria sunt his, malane? Illi enim inter se dissentiunt. </p>\n\n<p>Quodsi ipsam honestatem undique pertectam atque absolutam. Haeret in salebra. Id mihi magnum videtur. Quantum Aristoxeni ingenium consumptum videmus in musicis? Quo modo autem philosophus loquitur? Tenent mordicus. </p>\n\n<p>Quare conare, quaeso. Nulla erit controversia. Polycratem Samium felicem appellabant. Duo Reges: constructio interrete. Si id dicis, vicimus. Confecta res esset. Qui est in parvis malis. Dicimus aliquem hilare vivere; </p>\n\n', 1602076830),
(48, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pauca mutat vel plura sane; Cur haec eadem Democritus? Nam Pyrrho, Aristo, Erillus iam diu abiecti. Duo Reges: constructio interrete. </p>\n\n<p>Itaque his sapiens semper vacabit. At hoc in eo M. Disserendi artem nullam habuit. Summum a vobis bonum voluptas dicitur. Immo videri fortasse. </p>\n\n<p>Vide, quaeso, rectumne sit. Quid enim est a Chrysippo praetermissum in Stoicis? Eadem nunc mea adversum te oratio est. Utilitatis causa amicitia est quaesita. </p>\n\n', 1602076830),
(49, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et quidem, inquit, vehementer errat; Sed ad bona praeterita redeamus. Tubulo putas dicere? Si id dicis, vicimus. </p>\n\n<p>Quae cum dixisset, finem ille. Videsne quam sit magna dissensio? Quid me istud rogas? </p>\n\n<p>Duo Reges: constructio interrete. Moriatur, inquit. Quis est, qui non oderit libidinosam, protervam adolescentiam? </p>\n\n', 1602076830),
(50, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ita multa dicunt, quae vix intellegam. Uterque enim summo bono fruitur, id est voluptate. Quo igitur, inquit, modo? Duo Reges: constructio interrete. Sed fortuna fortis; Ait enim se, si uratur, Quam hoc suave! dicturum. </p>\n\n<p>Facillimum id quidem est, inquam. An tu me de L. Si longus, levis dictata sunt. Ut aliquid scire se gaudeant? </p>\n\n<p>Haec dicuntur inconstantissime. Illa tamen simplicia, vestra versuta. An nisi populari fama? Eam tum adesse, cum dolor omnis absit; Sin aliud quid voles, postea. </p>\n\n', 1602076830),
(51, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid enim de amicitia statueris utilitatis causa expetenda vides. Duo Reges: constructio interrete. Quod ea non occurrentia fingunt, vincunt Aristonem; Qui est in parvis malis. Quamquam id quidem licebit iis existimare, qui legerint. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. </p>\n\n<p>Est, ut dicis, inquit; Sed tamen intellego quid velit. Pollicetur certe. Sed ad illum redeo. </p>\n\n<p>Sed residamus, inquit, si placet. Sed in rebus apertissimis nimium longi sumus. Quid, de quo nulla dissensio est? Eam stabilem appellas. Urgent tamen et nihil remittunt. Murenam te accusante defenderem. </p>\n\n', 1602076831),
(52, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At, si voluptas esset bonum, desideraret. Aliter enim nosmet ipsos nosse non possumus. Quo tandem modo? Qui est in parvis malis. Omnia contraria, quos etiam insanos esse vultis. Age sane, inquam. </p>\n\n<p>Quid ait Aristoteles reliquique Platonis alumni? Duo Reges: constructio interrete. Est enim effectrix multarum et magnarum voluptatum. Bonum patria: miserum exilium. Id mihi magnum videtur. Frater et T. </p>\n\n<p>Invidiosum nomen est, infame, suspectum. Ita prorsus, inquam; Nescio quo modo praetervolavit oratio. Ego vero isti, inquam, permitto. Oratio me istius philosophi non offendit; Illa argumenta propria videamus, cur omnia sint paria peccata. </p>\n\n', 1602076831),
(53, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Rationis enim perfectio est virtus; Paulum, cum regem Persem captum adduceret, eodem flumine invectio? A mene tu? Non laboro, inquit, de nomine. Nos commodius agimus. </p>\n\n<p>Quid ergo? Duo Reges: constructio interrete. Quod ea non occurrentia fingunt, vincunt Aristonem; Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Et nemo nimium beatus est; Hoc sic expositum dissimile est superiori. </p>\n\n<p>Huius ego nunc auctoritatem sequens idem faciam. Quid dubitas igitur mutare principia naturae? Non est igitur summum malum dolor. </p>\n\n', 1602076831),
(54, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Efficiens dici potest. Quid enim possumus hoc agere divinius? Quae cum dixisset, finem ille. Laboro autem non sine causa; Duo Reges: constructio interrete. Aliter homines, aliter philosophos loqui putas oportere? Rationis enim perfectio est virtus; Eam tum adesse, cum dolor omnis absit; </p>\n\n<p>Nemo igitur esse beatus potest. Duarum enim vitarum nobis erunt instituta capienda. Paria sunt igitur. Inde igitur, inquit, ordiendum est. </p>\n\n<p>Quia dolori non voluptas contraria est, sed doloris privatio. Quid de Platone aut de Democrito loquar? Nihil illinc huc pervenit. Aliter enim nosmet ipsos nosse non possumus. Summum ením bonum exposuit vacuitatem doloris; Si longus, levis; Duarum enim vitarum nobis erunt instituta capienda. </p>\n\n', 1602076831),
(55, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Efficiens dici potest. Sed ille, ut dixi, vitiose. Suo genere perveniant ad extremum; Negat esse eam, inquit, propter se expetendam. </p>\n\n<p>Duo Reges: constructio interrete. Recte dicis; Tu quidem reddes; Illi enim inter se dissentiunt. Cur igitur, inquam, res tam dissimiles eodem nomine appellas? Quid ad utilitatem tantae pecuniae? </p>\n\n<p>Nam de isto magna dissensio est. Maximus dolor, inquit, brevis est. Bonum integritas corporis: misera debilitas. </p>\n\n', 1602076831),
(56, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quae tandem ista ratio est? Duo Reges: constructio interrete. Sed nunc, quod agimus; Respondent extrema primis, media utrisque, omnia omnibus. Hoc mihi cum tuo fratre convenit. </p>\n\n<p>An eiusdem modi? Recte, inquit, intellegis. Quis enim redargueret? Immo videri fortasse. Diodorus, eius auditor, adiungit ad honestatem vacuitatem doloris. </p>\n\n<p>Quare attende, quaeso. Eadem nunc mea adversum te oratio est. Ad eos igitur converte te, quaeso. Est, ut dicis, inquit; </p>\n\n', 1602078116),
(57, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eaedem res maneant alio modo. Esse enim quam vellet iniquus iustus poterat inpune. An eiusdem modi? Si id dicis, vicimus. </p>\n\n<p>Stoicos roga. Nihil opus est exemplis hoc facere longius. Restinguet citius, si ardentem acceperit. Quamquam te quidem video minime esse deterritum. Sint ista Graecorum; In schola desinis. </p>\n\n<p>Quae duo sunt, unum facit. Itaque fecimus. Duo Reges: constructio interrete. Qui convenit? </p>\n\n', 1602078117),
(58, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Frater et T. De hominibus dici non necesse est. Suo genere perveniant ad extremum; </p>\n\n<p>Quonam, inquit, modo? At, si voluptas esset bonum, desideraret. Respondeat totidem verbis. Nunc omni virtuti vitium contrario nomine opponitur. </p>\n\n<p>Sed videbimus. Duo Reges: constructio interrete. Si enim ad populum me vocas, eum. Iam id ipsum absurdum, maximum malum neglegi. Philosophi autem in suis lectulis plerumque moriuntur. Sed vos squalidius, illorum vides quam niteat oratio. Quid censes in Latino fore? </p>\n\n', 1602078117),
(59, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cui Tubuli nomen odio non est? Quis Aristidem non mortuum diligit? Ne amores quidem sanctos a sapiente alienos esse arbitrantur. Duo Reges: constructio interrete. </p>\n\n<p>Eam tum adesse, cum dolor omnis absit; Istam voluptatem, inquit, Epicurus ignorat? Que Manilium, ab iisque M. Tum Quintus: Est plane, Piso, ut dicis, inquit. </p>\n\n<p>Isto modo ne improbos quidem, si essent boni viri. Ita multa dicunt, quae vix intellegam. Utram tandem linguam nescio? Tecum optime, deinde etiam cum mediocri amico. </p>\n\n', 1602078117),
(60, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod quidem iam fit etiam in Academia. Nescio quo modo praetervolavit oratio. Ego vero isti, inquam, permitto. At iam decimum annum in spelunca iacet. Efficiens dici potest. </p>\n\n<p>Quis hoc dicit? Nihil opus est exemplis hoc facere longius. Certe non potest. Quis non odit sordidos, vanos, leves, futtiles? Suo genere perveniant ad extremum; Haec para/doca illi, nos admirabilia dicamus. A mene tu? Et quod est munus, quod opus sapientiae? </p>\n\n<p>Tu quidem reddes; At hoc in eo M. Duo Reges: constructio interrete. Efficiens dici potest. Bestiarum vero nullum iudicium puto. </p>\n\n', 1602078117),
(61, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos commodius agimus. Immo alio genere; Quis Aristidem non mortuum diligit? Age sane, inquam. </p>\n\n<p>Tibi hoc incredibile, quod beatissimum. Cum audissem Antiochum, Brute, ut solebam, cum M. Disserendi artem nullam habuit. Tibi hoc incredibile, quod beatissimum. </p>\n\n<p>Duo Reges: constructio interrete. Dicimus aliquem hilare vivere; Quis istud possit, inquit, negare? Sed quot homines, tot sententiae; Sic enim censent, oportunitatis esse beate vivere. Illa tamen simplicia, vestra versuta. </p>\n\n', 1602078117),
(62, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed haec omittamus; Iam contemni non poteris. Tria genera bonorum; Sed haec nihil sane ad rem; Duo Reges: constructio interrete. Sedulo, inquam, faciam. </p>\n\n<p>Quae cum dixisset paulumque institisset, Quid est? Vide, quantum, inquam, fallare, Torquate. Nihil opus est exemplis hoc facere longius. Non est ista, inquam, Piso, magna dissensio. </p>\n\n<p>Respondent extrema primis, media utrisque, omnia omnibus. Gerendus est mos, modo recte sentiat. Est enim effectrix multarum et magnarum voluptatum. Quo modo autem philosophus loquitur? </p>\n\n', 1602078118),
(63, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ratio quidem vestra sic cogit. Videsne quam sit magna dissensio? Omnis enim est natura diligens sui. Beatus sibi videtur esse moriens. Duo Reges: constructio interrete. Is es profecto tu. Non potes, nisi retexueris illa. </p>\n\n<p>Quibus ego vehementer assentior. Nunc agendum est subtilius. Non dolere, inquam, istud quam vim habeat postea videro; Oratio me istius philosophi non offendit; Summae mihi videtur inscitiae. Verum hoc idem saepe faciamus. </p>\n\n<p>At iam decimum annum in spelunca iacet. Omnia peccata paria dicitis. Quonam, inquit, modo? Illa tamen simplicia, vestra versuta. Qui ita affectus, beatum esse numquam probabis; At multis malis affectus. </p>\n\n', 1602078118),
(64, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ad utilitatem tantae pecuniae? Sed ego in hoc resisto; </p>\n\n<p>Duo enim genera quae erant, fecit tria. Is es profecto tu. Gerendus est mos, modo recte sentiat. Ego vero isti, inquam, permitto. Quod quidem iam fit etiam in Academia. Duo Reges: constructio interrete. </p>\n\n<p>Verum hoc idem saepe faciamus. Nihil opus est exemplis hoc facere longius. Itaque his sapiens semper vacabit. An eiusdem modi? </p>\n\n', 1602078118),
(65, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos commodius agimus. Si longus, levis dictata sunt. Quae contraria sunt his, malane? Duo Reges: constructio interrete. Ne discipulum abducam, times. Quae similitudo in genere etiam humano apparet. </p>\n\n<p>Pollicetur certe. Ad eos igitur converte te, quaeso. Age, inquies, ista parva sunt. Sin aliud quid voles, postea. Bonum incolumis acies: misera caecitas. Quam ob rem tandem, inquit, non satisfacit? </p>\n\n<p>Res enim concurrent contrariae. Murenam te accusante defenderem. Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Praeteritis, inquit, gaudeo. Sint ista Graecorum; Sed quae tandem ista ratio est? </p>\n\n', 1602078118),
(66, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Sed ego in hoc resisto; Si longus, levis dictata sunt. Quare attende, quaeso. </p>\n\n<p>Duo Reges: constructio interrete. Duarum enim vitarum nobis erunt instituta capienda. Tu quidem reddes; Ergo ita: non posse honeste vivi, nisi honeste vivatur? </p>\n\n<p>Praeclare hoc quidem. Quae cum essent dicta, discessimus. Sed in rebus apertissimis nimium longi sumus. Audeo dicere, inquit. Sed quae tandem ista ratio est? Haec dicuntur inconstantissime. </p>\n\n', 1602078118),
(67, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velut ego nunc moveor. Nunc vides, quid faciat. Sedulo, inquam, faciam. Id mihi magnum videtur. Non dolere, inquam, istud quam vim habeat postea videro; </p>\n\n<p>Quis hoc dicit? Duo Reges: constructio interrete. Pugnant Stoici cum Peripateticis. </p>\n\n<p>Non laboro, inquit, de nomine. Non autem hoc: igitur ne illud quidem. Quod iam a me expectare noli. Hoc loco tenere se Triarius non potuit. Quare conare, quaeso. Quis istud, quaeso, nesciebat? Non est igitur voluptas bonum. </p>\n\n', 1602078118),
(68, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Huius ego nunc auctoritatem sequens idem faciam. Id enim natura desiderat. ALIO MODO. Itaque contra est, ac dicitis; Duo Reges: constructio interrete. Nos commodius agimus. Quae sequuntur igitur? </p>\n\n<p>Equidem, sed audistine modo de Carneade? Haec quo modo conveniant, non sane intellego. Cur id non ita fit? Non potes, nisi retexueris illa. Istic sum, inquit. Bonum patria: miserum exilium. </p>\n\n<p>Haec dicuntur fortasse ieiunius; At eum nihili facit; Solum praeterea formosum, solum liberum, solum civem, stultost; Gerendus est mos, modo recte sentiat. Quid autem habent admirationis, cum prope accesseris? </p>\n\n', 1602078118),
(69, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tum Triarius: Posthac quidem, inquit, audacius. Sed quot homines, tot sententiae; Efficiens dici potest. Tollenda est atque extrahenda radicitus. Paria sunt igitur. </p>\n\n<p>Quo modo autem philosophus loquitur? Videsne quam sit magna dissensio? Omnia contraria, quos etiam insanos esse vultis. Tum Triarius: Posthac quidem, inquit, audacius. Addidisti ad extremum etiam indoctum fuisse. Quod cum dixissent, ille contra. </p>\n\n<p>Duo Reges: constructio interrete. Tum Torquatus: Prorsus, inquit, assentior; At iam decimum annum in spelunca iacet. Etiam beatissimum? </p>\n\n', 1602078118),
(70, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ratio quidem vestra sic cogit. Cyrenaici quidem non recusant; Hanc ergo intuens debet institutum illud quasi signum absolvere. Nihil ad rem! Ne sit sane; Ex rebus enim timiditas, non ex vocabulis nascitur. Tum Torquatus: Prorsus, inquit, assentior; </p>\n\n<p>Hoc enim constituto in philosophia constituta sunt omnia. Restinguet citius, si ardentem acceperit. </p>\n\n<p>Duo Reges: constructio interrete. Nihil opus est exemplis hoc facere longius. Cur, nisi quod turpis oratio est? Zenonis est, inquam, hoc Stoici. </p>\n\n', 1602078118),
(71, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Expectoque quid ad id, quod quaerebam, respondeas. Duo Reges: constructio interrete. Honesta oratio, Socratica, Platonis etiam. Quis istud possit, inquit, negare? Nam quid possumus facere melius? Itaque contra est, ac dicitis; Quae quo sunt excelsiores, eo dant clariora indicia naturae. </p>\n\n<p>Videmus igitur ut conquiescere ne infantes quidem possint. Quamquam id quidem licebit iis existimare, qui legerint. Non laboro, inquit, de nomine. Et quod est munus, quod opus sapientiae? At hoc in eo M. Sed ego in hoc resisto; </p>\n\n<p>Contemnit enim disserendi elegantiam, confuse loquitur. Quod cum dixissent, ille contra. Sed ille, ut dixi, vitiose. Conferam avum tuum Drusum cum C. Quid sequatur, quid repugnet, vident. Hic nihil fuit, quod quaereremus. </p>\n\n', 1602078119),
(72, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tum mihi Piso: Quid ergo? Illi enim inter se dissentiunt. De illis, cum volemus. Idemque diviserunt naturam hominis in animum et corpus. Et nemo nimium beatus est; </p>\n\n<p>Nescio quo modo praetervolavit oratio. Duo Reges: constructio interrete. Sed fortuna fortis; Contemnit enim disserendi elegantiam, confuse loquitur. Omnia peccata paria dicitis. Nihil ad rem! Ne sit sane; </p>\n\n<p>Quonam modo? Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Cave putes quicquam esse verius. Quare conare, quaeso. Nemo nostrum istius generis asotos iucunde putat vivere. Quo igitur, inquit, modo? Quis istud, quaeso, nesciebat? </p>\n\n', 1602078119),
(73, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut optime, secundum naturam affectum esse possit. Quis Aristidem non mortuum diligit? Hanc ergo intuens debet institutum illud quasi signum absolvere. Sed fortuna fortis; Duo Reges: constructio interrete. Prioris generis est docilitas, memoria; Nemo igitur esse beatus potest. Quorum altera prosunt, nocent altera. </p>\n\n<p>Efficiens dici potest. An eiusdem modi? Quantum Aristoxeni ingenium consumptum videmus in musicis? Praeclare hoc quidem. Negare non possum. Videsne, ut haec concinant? Zenonis est, inquam, hoc Stoici. Est, ut dicis, inquam. </p>\n\n<p>Maximas vero virtutes iacere omnis necesse est voluptate dominante. Iam in altera philosophiae parte. Hoc enim constituto in philosophia constituta sunt omnia. Sed tamen intellego quid velit. Frater et T. Consequens enim est et post oritur, ut dixi. </p>\n\n', 1602078119),
(74, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Videsne, ut haec concinant? Uterque enim summo bono fruitur, id est voluptate. Apparet statim, quae sint officia, quae actiones. Duo Reges: constructio interrete. Istam voluptatem, inquit, Epicurus ignorat? Immo alio genere; </p>\n\n<p>Aliter enim nosmet ipsos nosse non possumus. Sed quod proximum fuit non vidit. Aperiendum est igitur, quid sit voluptas; De vacuitate doloris eadem sententia erit. Ecce aliud simile dissimile. At certe gravius. </p>\n\n<p>Sit enim idem caecus, debilis. Satis est ad hoc responsum. At certe gravius. Non risu potius quam oratione eiciendum? Velut ego nunc moveor. Res enim concurrent contrariae. Bonum negas esse divitias, praeposìtum esse dicis? </p>\n\n', 1602078119),
(75, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praeteritis, inquit, gaudeo. Istam voluptatem perpetuam quis potest praestare sapienti? Si longus, levis; Non risu potius quam oratione eiciendum? </p>\n\n<p>Ea possunt paria non esse. Sed ne, dum huic obsequor, vobis molestus sim. Duo Reges: constructio interrete. Sed ad bona praeterita redeamus. Sed ad rem redeamus; Haec dicuntur inconstantissime. Si quae forte-possumus. </p>\n\n<p>Facillimum id quidem est, inquam. Hic ambiguo ludimur. Is es profecto tu. Eaedem res maneant alio modo. Cui Tubuli nomen odio non est? </p>\n\n', 1602078119),
(76, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Inquit, dasne adolescenti veniam? Peccata paria. Si longus, levis; Quippe: habes enim a rhetoribus; </p>\n\n<p>Duo Reges: constructio interrete. Quae cum dixisset paulumque institisset, Quid est? Graccho, eius fere, aequalí? </p>\n\n<p>Si longus, levis. Oratio me istius philosophi non offendit; An est aliquid, quod te sua sponte delectet? Maximus dolor, inquit, brevis est. Quae in controversiam veniunt, de iis, si placet, disseramus. Bonum negas esse divitias, praeposìtum esse dicis? Eam stabilem appellas. Quid est igitur, inquit, quod requiras? </p>\n\n', 1602078119);
INSERT INTO `lore` (`id`, `content`, `date`) VALUES
(77, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qui convenit? Quid autem habent admirationis, cum prope accesseris? Qui est in parvis malis. Tamen a proposito, inquam, aberramus. Prodest, inquit, mihi eo esse animo. Verum hoc idem saepe faciamus. </p>\n\n<p>Duo Reges: constructio interrete. Duo enim genera quae erant, fecit tria. Videamus igitur sententias eorum, tum ad verba redeamus. Nulla erit controversia. Est enim effectrix multarum et magnarum voluptatum. </p>\n\n<p>Bonum incolumis acies: misera caecitas. Quo studio Aristophanem putamus aetatem in litteris duxisse? Cur iustitia laudatur? Quam ob rem tandem, inquit, non satisfacit? Aliter enim nosmet ipsos nosse non possumus. Graccho, eius fere, aequalí? Tu quidem reddes; </p>\n\n', 1602078119),
(78, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iam id ipsum absurdum, maximum malum neglegi. Nunc de hominis summo bono quaeritur; At iste non dolendi status non vocatur voluptas. Que Manilium, ab iisque M. </p>\n\n<p>An hoc usque quaque, aliter in vita? Quonam modo? </p>\n\n<p>Duo Reges: constructio interrete. Eadem fortitudinis ratio reperietur. Eam tum adesse, cum dolor omnis absit; Videsne quam sit magna dissensio? Est, ut dicis, inquam. Cur deinde Metrodori liberos commendas? Maximus dolor, inquit, brevis est. A mene tu? </p>\n\n', 1602078119),
(79, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis hoc dicit? Quamquam id quidem, infinitum est in hac urbe; Egone quaeris, inquit, quid sentiam? Scrupulum, inquam, abeunti; </p>\n\n<p>Praeteritis, inquit, gaudeo. Immo alio genere; Tum mihi Piso: Quid ergo? Graece donan, Latine voluptatem vocant. Mihi, inquam, qui te id ipsum rogavi? Duarum enim vitarum nobis erunt instituta capienda. </p>\n\n<p>Duo Reges: constructio interrete. At enim hic etiam dolore. </p>\n\n', 1602078119),
(80, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc simile tandem est? Quae similitudo in genere etiam humano apparet. Quia nec honesto quic quam honestius nec turpi turpius. Duo Reges: constructio interrete. </p>\n\n<p>Quacumque enim ingredimur, in aliqua historia vestigium ponimus. Refert tamen, quo modo. Quis istum dolorem timet? Sumenda potius quam expetenda. </p>\n\n<p>Bonum incolumis acies: misera caecitas. At, si voluptas esset bonum, desideraret. Quamquam id quidem licebit iis existimare, qui legerint. Eaedem res maneant alio modo. </p>\n\n', 1602078119),
(81, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid igitur, inquit, eos responsuros putas? Quae similitudo in genere etiam humano apparet. Fortemne possumus dicere eundem illum Torquatum? Verum hoc idem saepe faciamus. Quamquam tu hanc copiosiorem etiam soles dicere. Vide, quantum, inquam, fallare, Torquate. </p>\n\n<p>Si longus, levis dictata sunt. Duo Reges: constructio interrete. Quod quidem nobis non saepe contingit. Quae cum essent dicta, discessimus. Iam in altera philosophiae parte. </p>\n\n<p>Hoc tu nunc in illo probas. Ita prorsus, inquam; Cave putes quicquam esse verius. Zenonis est, inquam, hoc Stoici. Eam tum adesse, cum dolor omnis absit; Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Odium autem et invidiam facile vitabis. Et quod est munus, quod opus sapientiae? </p>\n\n', 1602078120),
(82, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tecum optime, deinde etiam cum mediocri amico. Ergo id est convenienter naturae vivere, a natura discedere. Quis istud, quaeso, nesciebat? An tu me de L. Quo modo autem philosophus loquitur? </p>\n\n<p>Sint ista Graecorum; Scisse enim te quis coarguere possit? Duo Reges: constructio interrete. </p>\n\n<p>Suo enim quisque studio maxime ducitur. Nos commodius agimus. Negare non possum. Sed quid sentiat, non videtis. </p>\n\n', 1602078120),
(83, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod totum contra est. Iam in altera philosophiae parte. Ita multa dicunt, quae vix intellegam. Duo Reges: constructio interrete. Sed potestne rerum maior esse dissensio? Iam in altera philosophiae parte. </p>\n\n<p>Quare conare, quaeso. Quid est enim aliud esse versutum? Maximas vero virtutes iacere omnis necesse est voluptate dominante. Igitur ne dolorem quidem. </p>\n\n<p>Satis est ad hoc responsum. Frater et T. Disserendi artem nullam habuit. Immo alio genere; Velut ego nunc moveor. Itaque contra est, ac dicitis; </p>\n\n', 1602078120),
(84, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Et quod est munus, quod opus sapientiae? Restatis igitur vos; Primum in nostrane potestate est, quid meminerimus? Haec para/doca illi, nos admirabilia dicamus. Tibi hoc incredibile, quod beatissimum. </p>\n\n<p>Prioris generis est docilitas, memoria; Dat enim intervalla et relaxat. Mihi enim satis est, ipsis non satis. Primum quid tu dicis breve? </p>\n\n<p>Sed ad haec, nisi molestum est, habeo quae velim. Quid censes in Latino fore? </p>\n\n', 1602078120),
(85, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suo genere perveniant ad extremum; Odium autem et invidiam facile vitabis. Si longus, levis. Urgent tamen et nihil remittunt. Tollenda est atque extrahenda radicitus. Duo Reges: constructio interrete. Iam contemni non poteris. Hos contra singulos dici est melius. </p>\n\n<p>At certe gravius. Omnia contraria, quos etiam insanos esse vultis. Tecum optime, deinde etiam cum mediocri amico. Nam de isto magna dissensio est. </p>\n\n<p>Si id dicis, vicimus. Scisse enim te quis coarguere possit? Consequentia exquirere, quoad sit id, quod volumus, effectum. Haec dicuntur fortasse ieiunius; Si quidem, inquit, tollerem, sed relinquo. Scrupulum, inquam, abeunti; Rationis enim perfectio est virtus; Sequitur disserendi ratio cognitioque naturae; </p>\n\n', 1602078120),
(86, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eam tum adesse, cum dolor omnis absit; Videsne quam sit magna dissensio? Sed residamus, inquit, si placet. At, si voluptas esset bonum, desideraret. </p>\n\n<p>Tubulo putas dicere? Aperiendum est igitur, quid sit voluptas; At iam decimum annum in spelunca iacet. Itaque ab his ordiamur. </p>\n\n<p>Duo Reges: constructio interrete. Cur id non ita fit? Summus dolor plures dies manere non potest? Immo alio genere; Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Quod cum dixissent, ille contra. </p>\n\n', 1602078120),
(87, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id mihi magnum videtur. Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Tum Triarius: Posthac quidem, inquit, audacius. Cur iustitia laudatur? Sed quot homines, tot sententiae; Non est ista, inquam, Piso, magna dissensio. </p>\n\n<p>Duo Reges: constructio interrete. Res enim concurrent contrariae. Frater et T. Ut pulsi recurrant? Tibi hoc incredibile, quod beatissimum. Ea possunt paria non esse. ALIO MODO. </p>\n\n<p>Reguli reiciendam; Quarum ambarum rerum cum medicinam pollicetur, luxuriae licentiam pollicetur. Ratio quidem vestra sic cogit. Ut aliquid scire se gaudeant? Nos commodius agimus. </p>\n\n', 1602078120),
(88, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos vero, inquit ille; Istic sum, inquit. Praeteritis, inquit, gaudeo. Primum quid tu dicis breve? Ita prorsus, inquam; Teneo, inquit, finem illi videri nihil dolere. </p>\n\n<p>Age, inquies, ista parva sunt. Duo Reges: constructio interrete. Quae cum essent dicta, discessimus. Sit enim idem caecus, debilis. </p>\n\n<p>Tum ille timide vel potius verecunde: Facio, inquit. Primum divisit ineleganter; </p>\n\n', 1602078120),
(89, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid autem habent admirationis, cum prope accesseris? Ut proverbia non nulla veriora sint quam vestra dogmata. Hunc vos beatum; At enim hic etiam dolore. Duo Reges: constructio interrete. </p>\n\n<p>Consequens enim est et post oritur, ut dixi. Quippe: habes enim a rhetoribus; Sint modo partes vitae beatae. Duo enim genera quae erant, fecit tria. Quid autem habent admirationis, cum prope accesseris? Non potes, nisi retexueris illa. Quodsi ipsam honestatem undique pertectam atque absolutam. Quid de Platone aut de Democrito loquar? </p>\n\n<p>Eadem nunc mea adversum te oratio est. Non est igitur summum malum dolor. Qui ita affectus, beatum esse numquam probabis; Ratio quidem vestra sic cogit. Quis Aristidem non mortuum diligit? Ut optime, secundum naturam affectum esse possit. Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Simus igitur contenti his. Quonam, inquit, modo? </p>\n\n', 1602078120),
(90, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Primum divisit ineleganter; Cave putes quicquam esse verius. Satis est ad hoc responsum. Estne, quaeso, inquam, sitienti in bibendo voluptas? Cave putes quicquam esse verius. Haec para/doca illi, nos admirabilia dicamus. </p>\n\n<p>Pollicetur certe. Omnes enim iucundum motum, quo sensus hilaretur. At enim hic etiam dolore. Sed in rebus apertissimis nimium longi sumus. Peccata paria. Philosophi autem in suis lectulis plerumque moriuntur. </p>\n\n<p>Duo Reges: constructio interrete. Haec para/doca illi, nos admirabilia dicamus. </p>\n\n', 1602078120),
(91, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid est enim aliud esse versutum? Mihi enim erit isdem istis fortasse iam utendum. Sic enim censent, oportunitatis esse beate vivere. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. At certe gravius. Eaedem enim utilitates poterunt eas labefactare atque pervertere. Duo Reges: constructio interrete. Inde igitur, inquit, ordiendum est. </p>\n\n<p>Istam voluptatem perpetuam quis potest praestare sapienti? Ut pulsi recurrant? Estne, quaeso, inquam, sitienti in bibendo voluptas? Nulla erit controversia. Satis est ad hoc responsum. Quodsi ipsam honestatem undique pertectam atque absolutam. Sit enim idem caecus, debilis. Nemo igitur esse beatus potest. </p>\n\n<p>Sed fortuna fortis; Si enim ad populum me vocas, eum. Cur deinde Metrodori liberos commendas? Sed residamus, inquit, si placet. Odium autem et invidiam facile vitabis. Quid de Platone aut de Democrito loquar? Quae duo sunt, unum facit. </p>\n\n', 1602078121),
(92, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quare conare, quaeso. Quae contraria sunt his, malane? Videsne quam sit magna dissensio? Proclivi currit oratio. Duo Reges: constructio interrete. Proclivi currit oratio. </p>\n\n<p>Ac tamen hic mallet non dolere. Stoicos roga. Quid sequatur, quid repugnet, vident. </p>\n\n<p>Utilitatis causa amicitia est quaesita. Nos commodius agimus. Negat enim summo bono afferre incrementum diem. Quorum altera prosunt, nocent altera. </p>\n\n', 1602078121),
(93, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Venit ad extremum; Sed tamen intellego quid velit. Tollitur beneficium, tollitur gratia, quae sunt vincla concordiae. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? </p>\n\n<p>Re mihi non aeque satisfacit, et quidem locis pluribus. Duo Reges: constructio interrete. Tollenda est atque extrahenda radicitus. Sed haec nihil sane ad rem; Quibus ego vehementer assentior. Bonum incolumis acies: misera caecitas. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris? </p>\n\n<p>Quid adiuvas? Cur id non ita fit? Negat enim summo bono afferre incrementum diem. Quod quidem iam fit etiam in Academia. Bonum patria: miserum exilium. Sed ille, ut dixi, vitiose. </p>\n\n', 1602078121),
(94, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nosti, credo, illud: Nemo pius est, qui pietatem-; Primum quid tu dicis breve? Quis non odit sordidos, vanos, leves, futtiles? Cave putes quicquam esse verius. Multoque hoc melius nos veriusque quam Stoici. </p>\n\n<p>Sit enim idem caecus, debilis. Duo Reges: constructio interrete. Atqui reperies, inquit, in hoc quidem pertinacem; Tanta vis admonitionis inest in locis; Mihi enim satis est, ipsis non satis. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Sed virtutem ipsam inchoavit, nihil amplius. Cave putes quicquam esse verius. </p>\n\n<p>Quid igitur, inquit, eos responsuros putas? Praeclarae mortes sunt imperatoriae; Certe, nisi voluptatem tanti aestimaretis. Nihil illinc huc pervenit. Erit enim mecum, si tecum erit. Quae quidem sapientes sequuntur duce natura tamquam videntes; </p>\n\n', 1602078121),
(95, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc loco tenere se Triarius non potuit. Haec quo modo conveniant, non sane intellego. Hos contra singulos dici est melius. Quid censes in Latino fore? Istam voluptatem, inquit, Epicurus ignorat? </p>\n\n<p>Memini vero, inquam; Scisse enim te quis coarguere possit? Quid nunc honeste dicit? Duarum enim vitarum nobis erunt instituta capienda. Non laboro, inquit, de nomine. Est enim effectrix multarum et magnarum voluptatum. </p>\n\n<p>Proclivi currit oratio. Nunc omni virtuti vitium contrario nomine opponitur. Non semper, inquam; Duo Reges: constructio interrete. Minime vero istorum quidem, inquit. Equidem e Cn. </p>\n\n', 1602078121),
(96, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tollenda est atque extrahenda radicitus. Non quam nostram quidem, inquit Pomponius iocans; Id enim natura desiderat. Et quod est munus, quod opus sapientiae? Primum in nostrane potestate est, quid meminerimus? </p>\n\n<p>Sed tamen intellego quid velit. Scrupulum, inquam, abeunti; </p>\n\n<p>Non est igitur voluptas bonum. Duo Reges: constructio interrete. Quacumque enim ingredimur, in aliqua historia vestigium ponimus. Inscite autem medicinae et gubernationis ultimum cum ultimo sapientiae comparatur. </p>\n\n', 1602078121),
(97, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Addidisti ad extremum etiam indoctum fuisse. Verum hoc idem saepe faciamus. Certe, nisi voluptatem tanti aestimaretis. Summum ením bonum exposuit vacuitatem doloris; Quacumque enim ingredimur, in aliqua historia vestigium ponimus. Qua tu etiam inprudens utebare non numquam. </p>\n\n<p>Duo Reges: constructio interrete. Quos quidem tibi studiose et diligenter tractandos magnopere censeo. Quid, si etiam iucunda memoria est praeteritorum malorum? Hoc loco tenere se Triarius non potuit. Qui est in parvis malis. Nos vero, inquit ille; </p>\n\n<p>Faceres tu quidem, Torquate, haec omnia; Huius, Lyco, oratione locuples, rebus ipsis ielunior. </p>\n\n', 1602078121),
(98, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. An eiusdem modi? Perge porro; Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Duo Reges: constructio interrete. </p>\n\n<p>Videsne, ut haec concinant? Nunc omni virtuti vitium contrario nomine opponitur. Cur, nisi quod turpis oratio est? Nunc de hominis summo bono quaeritur; </p>\n\n<p>Quantum Aristoxeni ingenium consumptum videmus in musicis? Quamquam te quidem video minime esse deterritum. ALIO MODO. Tu enim ista lenius, hic Stoicorum more nos vexat. Reguli reiciendam; Ita credo. </p>\n\n', 1602078121),
(99, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hunc vos beatum; Itaque hic ipse iam pridem est reiectus; Hoc est non dividere, sed frangere. Quo modo autem optimum, si bonum praeterea nullum est? Ac tamen hic mallet non dolere. Duo Reges: constructio interrete. </p>\n\n<p>Quis istud possit, inquit, negare? Quae quo sunt excelsiores, eo dant clariora indicia naturae. Sed residamus, inquit, si placet. Efficiens dici potest. </p>\n\n<p>Ea possunt paria non esse. Recte, inquit, intellegis. Quod iam a me expectare noli. Hoc non est positum in nostra actione. Nunc omni virtuti vitium contrario nomine opponitur. Quid ad utilitatem tantae pecuniae? Gloriosa ostentatio in constituendo summo bono. </p>\n\n', 1602078121),
(100, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Rhetorice igitur, inquam, nos mavis quam dialectice disputare? Iam id ipsum absurdum, maximum malum neglegi. Equidem e Cn. Qui est in parvis malis. ALIO MODO. Duo Reges: constructio interrete. </p>\n\n<p>Omnis enim est natura diligens sui. Equidem e Cn. Negare non possum. Quippe: habes enim a rhetoribus; Quod ea non occurrentia fingunt, vincunt Aristonem; Primum divisit ineleganter; </p>\n\n<p>Sed quod proximum fuit non vidit. Satis est ad hoc responsum. Nullus est igitur cuiusquam dies natalis. Ex rebus enim timiditas, non ex vocabulis nascitur. </p>\n\n', 1602078121),
(101, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Idem iste, inquam, de voluptate quid sentit? Mihi, inquam, qui te id ipsum rogavi? Duo Reges: constructio interrete. Tum Quintus: Est plane, Piso, ut dicis, inquit. Quonam, inquit, modo? Ostendit pedes et pectus. </p>\n\n<p>Quamquam tu hanc copiosiorem etiam soles dicere. Prave, nequiter, turpiter cenabat; Philosophi autem in suis lectulis plerumque moriuntur. Duo enim genera quae erant, fecit tria. </p>\n\n<p>Quid sequatur, quid repugnet, vident. Primum divisit ineleganter; Recte dicis; Praeclare hoc quidem. Videamus animi partes, quarum est conspectus illustrior; Tamen a proposito, inquam, aberramus. Claudii libidini, qui tum erat summo ne imperio, dederetur. </p>\n\n', 1602078122),
(102, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Verum hoc idem saepe faciamus. Murenam te accusante defenderem. Praeteritis, inquit, gaudeo. Perge porro; At hoc in eo M. Duo Reges: constructio interrete. </p>\n\n<p>Sed ne, dum huic obsequor, vobis molestus sim. Cur haec eadem Democritus? Et nemo nimium beatus est; Nobis aliter videtur, recte secusne, postea; Nunc haec primum fortasse audientis servire debemus. </p>\n\n<p>Scisse enim te quis coarguere possit? Certe, nisi voluptatem tanti aestimaretis. Sic consequentibus vestris sublatis prima tolluntur. Contineo me ab exemplis. </p>\n\n', 1602078122),
(103, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam ob rem tandem, inquit, non satisfacit? Iam enim adesse poterit. Duo Reges: constructio interrete. Quae in controversiam veniunt, de iis, si placet, disseramus. </p>\n\n<p>Ego vero volo in virtute vim esse quam maximam; Idemne, quod iucunde? Quid ad utilitatem tantae pecuniae? Cur id non ita fit? Quae duo sunt, unum facit. Non est igitur voluptas bonum. </p>\n\n<p>Sed hoc sane concedamus. Non quam nostram quidem, inquit Pomponius iocans; Atqui reperies, inquit, in hoc quidem pertinacem; Tum ille timide vel potius verecunde: Facio, inquit. Quae ista amicitia est? Quod cum accidisset ut alter alterum necopinato videremus, surrexit statim. </p>\n\n', 1602078122),
(104, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quonam modo? Omnis enim est natura diligens sui. Eademne, quae restincta siti? Eaedem res maneant alio modo. Nam quid possumus facere melius? Duo Reges: constructio interrete. Restinguet citius, si ardentem acceperit. Tamen a proposito, inquam, aberramus. </p>\n\n<p>Quae cum essent dicta, discessimus. Hoc non est positum in nostra actione. Quis istud possit, inquit, negare? </p>\n\n<p>Facillimum id quidem est, inquam. Quid Zeno? Cur iustitia laudatur? Sed plane dicit quod intellegit. Bonum integritas corporis: misera debilitas. Iam id ipsum absurdum, maximum malum neglegi. Sed ad illum redeo. Sint ista Graecorum; </p>\n\n', 1602078122),
(105, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliter homines, aliter philosophos loqui putas oportere? Nescio quo modo praetervolavit oratio. Haec para/doca illi, nos admirabilia dicamus. Duo Reges: constructio interrete. Immo alio genere; Non est igitur summum malum dolor. </p>\n\n<p>Nam quid possumus facere melius? Sullae consulatum? Nullus est igitur cuiusquam dies natalis. Iam in altera philosophiae parte. Quid dubitas igitur mutare principia naturae? Nescio quo modo praetervolavit oratio. </p>\n\n<p>Conferam avum tuum Drusum cum C. Restinguet citius, si ardentem acceperit. Negat esse eam, inquit, propter se expetendam. Quis enim redargueret? </p>\n\n', 1602078122);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `lore`
--
ALTER TABLE `lore`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `lore`
--
ALTER TABLE `lore`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=106;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
